---
# tasks file for logrotate (Ubuntu specific)

- name: Install logrotate packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ logrotate_packages }}"
  tags:
    - logrotate
